# Generated by Django 3.0.7 on 2020-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0002_auto_20200616_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='profile_title',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
