# Generated by Django 3.0.7 on 2020-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0004_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='connections',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
