# Generated by Django 3.0.7 on 2020-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0006_auto_20200620_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='map_embad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
